apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: s2egz62xz-nodejs
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe:fc0e98feda16a5c664cc203155361e0d38fb6e04@sha256:93b4e34a825fd7d1df5c712a274ff9857c6f64254e26df59c351333ecfe1e58f
          name: container-image
